apiVersion: v1
kind: Namespace
metadata:
  name: mimikube-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # название деплоймента
  name: coordinator-deployment
  namespace: mimikube-dev
  labels:
    app: coordinator-label
spec:
  # Количество реплик
  replicas: 1
  # Указывает, с какими подами будет работать деплоймент
  selector:
    #Поды, у которых есть такой label
    matchLabels:
      project: coordinator-pod
    #Описание подов этого деплоймента
  template:
    metadata:
      name: coordinator-pod
      #Очевидно, что должны быть такие же labels, какие мы указали в matchLabels в деплойменте
      labels:
        project: coordinator-pod
    spec:
      #Описываем, какие контейнеры будут в этом поде
      containers:
        - name: coordinator-container
          image: coordinator
          # образ никогда не будет скачиваться из-вне, только из имеющихся уже на устройстве локально
          imagePullPolicy: Never
          ports:
            - containerPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: mimikube
  labels:
    app: user-label
spec:
  selector:
    matchLabels:
      project: user-pod
  template:
    metadata:
      name: user-pod
      labels:
        project: user-pod
    spec:
      containers:
        - name: user-container
          image: user
          imagePullPolicy: Never
          ports:
            - containerPort: 8083