apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: mimikube-dev
type: Opaque
# кодировка в base64
data:
  DB_HOST: MTkyLjE2OC4wLjEwNA==   # 192.160.0.104
  DB_PORT: NTQzMw==               # 5433
  DB_USER: ZGltYQ==               # dima
  DB_PASSWORD: MTIzNHF3ZXI=       # 1234qwer