server:
  port: 8083

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metric

spring:
  datasource:
    username: dima
    password: 1234qwer
    url: jdbc:postgresql://localhost:5433/mimikube
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true