global:
  scrape_interval: 20s
  scrape_timeout: 10s
  evaluation_interval: 20s

scrape_configs:
  - job_name: user-service
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['test.info:8082']