apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: mimikube-dev
  labels:
    app: agent-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: agent-pod
  template:
    metadata:
      name: agent-pod
      labels:
        name: agent-pod
    spec:
      containers:
        - name: agent-container
          image: prom/prometheus:latest
          volumeMounts:
            - name: configs
              mountPath: "/etc/prometheus"
          ports:
            - containerPort: 9090
      volumes:
        - name: configs
          configMap:
            name: agent-config-map